[LegalNotice]
Accepted=true

[BitTorrent]
Session\Port=6881
Session\DHTEnabled=false
Session\LSDEnabled=false
Session\PeXEnabled=false
Session\Encryption=0
Session\DisableAutoTMMByDefault=true
Session\DefaultSavePath=/interop/qbit
Session\QueueingSystemEnabled=false

[Preferences]
WebUI\Port=8080
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=0.0.0.0/0
WebUI\LocalHostAuth=false
WebUI\HostHeaderValidation=false
WebUI\CSRFProtection=false
